///*
// * Copyright 2016 rudz.
// *
// * Licensed under the Apache License, Version 2.0 (the "License");
// * you may not use this file except in compliance with the License.
// * You may obtain a copy of the License at
// *
// *      http://www.apache.org/licenses/LICENSE-2.0
// *
// * Unless required by applicable law or agreed to in writing, software
// * distributed under the License is distributed on an "AS IS" BASIS,
// * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// * See the License for the specific language governing permissions and
// * limitations under the License.
// */
//package ui;
//
//import java.awt.GridLayout;
//import javax.swing.JFrame;
//import javax.swing.JPanel;
//import javax.swing.JTextField;
//import static ui.UI.getColor;
//import static ui.UI.isLocal;
//
///**
// *
// * @author rudz
// */
//public class UI_old {
//    
//        /**
//     * Autogenerated ship layout on playing board
//     * @param u
//     * @param t
//     * @return 
//     */
//    public JPanel autoBoard(int u, int t) {
//
//        PLAYERS[u].setGBoard(new JPanel(new GridLayout(11, 11)));//panel to store board		
//        JTextField k;
//        if (!"Unknown".equals(PLAYERS[u].getUser())) {
//            for (int i = 0; i < 5; i++) {
//                PLAYERS[u].setBoats(i, PLAYERS[u].getBoats(i).compinput(i, u));
//            }
//        }
//        for (int i = 0; i < 11; i++) {
//            for (int j = 0; j < 11; j++) {
//                if (j != 0 && i != 0) {
//                    if ("Computer".equals(PLAYERS[u].getUser()) || isLocal()) {
//                        PLAYERS[u].getBboard(i - 1, j - 1).addActionListener(new AttackListener());
//                    } else if ("Computer".equals(PLAYERS[t].getUser()) || "CPU1".equals(PLAYERS[t].getUser()) || "CPU2".equals(PLAYERS[t].getUser()) || "Unknown".equals(PLAYERS[t].getUser())) {
//                        if (PLAYERS[u].getHitOrMiss(i - 1, j - 1)) {
//                            PLAYERS[u].setBboard(i - 1, j - 1, getColor());
//                        }
//                    } else {
//                        PLAYERS[u].getBboard(i - 1, j - 1).addActionListener(new InternetListener());
//                    }
//                    PLAYERS[u].getGBoard().add(PLAYERS[u].getBboard(i - 1, j - 1));
//                }
//                if (i == 0) {
//                    if (j != 0) {
//                        //used to display row of numbers
//                        k = new JTextField(UI.getCnumbers(j));
//                        k.setEditable(false);
//                        k.setHorizontalAlignment((int) JFrame.CENTER_ALIGNMENT);
//                    } else {
//                        //used to display column of numbers
//                        k = new JTextField();
//                        k.setEditable(false);
//                    }
//                    PLAYERS[u].getGBoard().add(k);
//                } else if (j == 0) {
//                    k = new JTextField(UI.getCletters(i));
//                    k.setEditable(false);
//                    k.setHorizontalAlignment((int) JFrame.CENTER_ALIGNMENT);
//                    PLAYERS[u].getGBoard().add(k);
//                }
//            }
//        }
//        return PLAYERS[u].getGBoard();
//    }
//
//}
